<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            color: #333;
            font-size: 24px;
        }
        .header .meta {
            margin: 10px 0 0;
            color: #666;
            font-size: 11px;
        }
        .content {
            text-align: justify;
            margin-bottom: 30px;
        }
        .content h1, .content h2, .content h3 {
            color: #333;
            margin: 20px 0 10px;
        }
        .content h1 { font-size: 18px; }
        .content h2 { font-size: 16px; }
        .content h3 { font-size: 14px; }
        .content p {
            margin: 10px 0;
        }
        .content ul, .content ol {
            margin: 10px 0;
            padding-left: 20px;
        }
        .content table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        .content table th,
        .content table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .content table th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #eee;
            padding-top: 15px;
        }
        .page-break {
            page-break-before: always;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <div class="meta">
            Generated on {{ $generated_at->format('F j, Y \a\t g:i A') }} by {{ $generated_by }}
        </div>
    </div>

    <div class="content">
        {!! nl2br(e($content)) !!}
    </div>

    <div class="footer">
        <p>This document was generated by the Admin Panel System | {{ config('app.name') }}</p>
        <p>Generated on {{ $generated_at->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>
