<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>News Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #333;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            color: #333;
            font-size: 24px;
        }
        .header p {
            margin: 5px 0 0;
            color: #666;
        }
        .filters {
            background-color: #f8f9fa;
            padding: 15px;
            margin-bottom: 20px;
            border-radius: 5px;
        }
        .filters h3 {
            margin: 0 0 10px;
            font-size: 14px;
            color: #333;
        }
        .filter-item {
            display: inline-block;
            margin-right: 20px;
            margin-bottom: 5px;
        }
        .news-item {
            border-bottom: 1px solid #eee;
            padding-bottom: 15px;
            margin-bottom: 15px;
            page-break-inside: avoid;
        }
        .news-item:last-child {
            border-bottom: none;
        }
        .news-title {
            font-size: 16px;
            font-weight: bold;
            color: #333;
            margin: 0 0 5px;
        }
        .news-meta {
            color: #666;
            font-size: 11px;
            margin-bottom: 8px;
        }
        .news-content {
            color: #444;
            text-align: justify;
            margin-bottom: 8px;
        }
        .status-badge {
            padding: 2px 8px;
            border-radius: 3px;
            font-size: 10px;
            font-weight: bold;
        }
        .status-published {
            background-color: #d4edda;
            color: #155724;
        }
        .status-draft {
            background-color: #fff3cd;
            color: #856404;
        }
        .summary {
            background-color: #e9ecef;
            padding: 15px;
            margin-top: 30px;
            border-radius: 5px;
        }
        .summary h3 {
            margin: 0 0 10px;
            font-size: 14px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
            border-top: 1px solid #eee;
            padding-top: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>News Report</h1>
        <p>Generated on {{ now()->format('F j, Y \a\t g:i A') }}</p>
    </div>

    <div class="filters">
        <h3>Report Filters:</h3>
        @if($request->date_from)
            <div class="filter-item"><strong>From:</strong> {{ \Carbon\Carbon::parse($request->date_from)->format('M j, Y') }}</div>
        @endif
        @if($request->date_to)
            <div class="filter-item"><strong>To:</strong> {{ \Carbon\Carbon::parse($request->date_to)->format('M j, Y') }}</div>
        @endif
        @if($request->status)
            <div class="filter-item"><strong>Status:</strong> {{ ucfirst($request->status) }}</div>
        @endif
        @if(!$request->date_from && !$request->date_to && !$request->status)
            <div class="filter-item">All news articles</div>
        @endif
    </div>

    @forelse($news as $article)
        <div class="news-item">
            <h2 class="news-title">{{ $article->title }}</h2>
            <div class="news-meta">
                <strong>Published:</strong> {{ $article->created_at->format('M j, Y g:i A') }} |
                <strong>Author:</strong> {{ $article->user->name ?? 'Unknown' }} |
                <strong>Category:</strong> {{ $article->category->name ?? 'Uncategorized' }} |
                <span class="status-badge status-{{ $article->status }}">{{ ucfirst($article->status) }}</span>
            </div>
            <div class="news-content">
                {{ strip_tags($article->excerpt ?: Str::limit($article->content, 200)) }}
            </div>
        </div>
    @empty
        <div style="text-align: center; padding: 50px; color: #666;">
            <p>No news articles found matching the specified criteria.</p>
        </div>
    @endforelse

    <div class="summary">
        <h3>Report Summary</h3>
        <p><strong>Total Articles:</strong> {{ $news->count() }}</p>
        <p><strong>Published:</strong> {{ $news->where('status', 'published')->count() }}</p>
        <p><strong>Draft:</strong> {{ $news->where('status', 'draft')->count() }}</p>
    </div>

    <div class="footer">
        <p>This report was generated by the Admin Panel System | {{ config('app.name') }}</p>
    </div>
</body>
</html>
